### ISSUE TITLE
Adjust FunctionHandler for returning struct

### ISSUE THREAD

**Issue by SebastianSpyrzewski** [mhorod/cacophony#240]
Change method `getResultRegister` in Function Handler to method returning `Variable` - described [here](https://github.com/mhorod/cacophony/blob/main/DEVELOPMENT.md#function-handler).

Adjust Epilogue and GenerateCall so it fits new call convention for structures - described [here](https://github.com/mhorod/cacophony/blob/main/DEVELOPMENT.md#function-call-and-return).

**Comment by FilipKon13** [comment]
Closed by #251
