### ISSUE TITLE
Add tests for findNullable, findFirst, findFollow

### ISSUE THREAD

**Issue by km1chno** [mhorod/cacophony#51]
This task requires to design manually several cases to cover most/all possibilities, manually
find correct `nullable`, `first` and `follow` and test if `findNullable`, `findFirst`, `findFollow` calculate the same thing.

>[!IMPORTANT]
>This is a really mundane task, so usage of AI for boilerplate is recommended.

**Comment by mhorod** [comment]
tests for `findNullable` merged (#63, #64)

**Comment by mhorod** [comment]
tests for find first merged (#67, #66)
