### ISSUE TITLE
Refactor I

### ISSUE THREAD

**Issue by km1chno** [mhorod/cacophony#58]
List of things to do:

- reconsider linter config, the are some things that are irritating to some people
- think of a convention for naming generic parameters and rename them, currently we don't have one. In several places they have suffix `Type`, but e.g. [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s5.2.8-type-variable-names) proposes suffix `T`

**Comment by Giselus** [comment]
Change test productions like this: `Pair(1, 'a') to 2` -> `1 via 'a' to 2`

**Comment by FilipKon13** [comment]
Move utility functions (`via`, `buildDFAFromRegex` etc.) from `DFAUtils.kt` outside of minimalization directory

**Comment by AHGIJMKLKKZNPJKQR** [comment]
Improve diagnostics to be more flexible (https://github.com/mhorod/cacophony/pull/70#discussion_r1818735313)

**Comment by MisieqqeisiM** [comment]
Create a superclass for all custom exceptions thrown during compilation

**Comment by FilipKon13** [comment]
Resolve #27
